# Default values for wg-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

configname: wireguard-config

image:
  repository: linuxserver/wireguard
  pullPolicy: IfNotPresent
  tag: 1.0.20250521

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "wg-k8s"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  privileged: true
  capabilities:
    add:
      - NET_ADMIN
      - SYS_MODULE

service:
  type: ClusterIP
  port: 4500

resources: {}

livenessProbe:
  exec:
    command:
      - /bin/sh
      - -c
      - "ss -lnu | grep -q 4500"
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  exec:
    command:
      - /bin/sh
      - -c
      - "ss -lnu | grep -q 4500"
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

gateway:
  create: true

  image:
    repository: vimagick/tinyproxy
    pullPolicy: IfNotPresent
    tag: latest

  service:
    type: ClusterIP

    ports: []
