---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config
data:
  wg0.conf.template: |
    [Interface]
    PrivateKey = ${PRIVATE_KEY}
    Address = {{ .Values.config.interface.address }}
    {{- if .Values.config.interface.dns }}
    DNS = {{ .Values.config.interface.dns }}
    {{- end }}
    {{- if .Values.config.interface.listenport }}
    ListenPort = {{ .Values.config.interface.listenport }}
    {{- end }}
    
    PostUp   = {{ .Values.config.postUp }}
    PostDown = {{ .Values.config.postDown }}

    {{- range .Values.config.peers }}

    [Peer]
    PublicKey = {{ .publicKey }}
    {{- if .endpoint }}
    Endpoint = {{ .endpoint }}
    {{- end }}
    AllowedIPs = {{ .allowedIPs }}
    {{- if .persistentKeepAlive }}
    PersistentKeepalive = {{ .persistentKeepAlive }}
    {{- end }}
    {{- end }}
---
