---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-k8s.fullname" . }}
  labels:
    {{- include "wg-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadbalancerip }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: UDP
  selector:
    {{- include "wg-k8s.selectorLabels" . | nindent 4 }}
---
