name: Build and Release
permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Install Helm
        uses: azure/setup-helm@v4
      
      - name: Install Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      
      - name: Install Chart Releaser via Homebrew
        run: |
          brew tap helm/tap
          brew install chart-releaser

      - name: Release chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          cr package wg-k8s
          cr upload --owner serrichard --token $CR_TOKEN --git-repo wg-k8s --packages-with-index --push --skip-existing 
          cr index --owner serrichard --token $CR_TOKEN --git-repo wg-k8s --packages-with-index --index-path . --push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update docs from release ${{ github.sha }}"
          title: "Update gh-pages after release"
          body: |
            This PR updates gh-pages after the release workflow.
          base: gh-pages
          branch: update-gh-pages-${{ github.run_id }}
