name: Build and Release
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          packages_with_index: True
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
